(maint) typecast $num_facts_per_agent
Prior to this, it is possible in some configurations for `$num_facts_per_agent`
to come in as an integer. Without converting to a string, this can generate
errors that look like:

```
Error: Failed to apply catalog: Parameter content failed on File[/etc/puppetlabs/clamps/num_facts]: Munging failed for value 500 in class content: no implicit conversion of Fixnum into String at /some/path:123>
```